language: generic

matrix:
  include:
    - os: linux
      name: Ubuntu Trusty
      dist: trusty
      sudo: required
    - os: osx
      name: macOS (Xcode10)
      osx_image: xcode10

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then swiftenv install 4.2-dev; fi
  - swift --version
  - bundle install

before_script:
  - bundle exec danger

script:
  - swift run test
